DD-2729 feat(SDK; Publishing): Add publish guard and use env variables for pushing tags
Verify before merging: ensure compliance with our [Secure Engineering Principles](https://solvimon.getoutline.com/s/21fbef7a-ff0d-4b88-ae5c-946546875f33) and [Definition of Done](https://solvimon.getoutline.com/doc/definition-of-done-90fb00NtJw).

Closes DD-2729

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -106,6 +106,11 @@ tag:sdk-release:
               exit 0
           fi
 
+          if [ -z "$SDK_RELEASE_USERNAME" ] || [ -z "$SDK_RELEASE_TOKEN" ]; then
+              echo "Missing SDK_RELEASE_USERNAME or SDK_RELEASE_TOKEN CI variable."
+              exit 1
+          fi
+
           VERSION="$(node -p "require('./packages/sdk/package.json').version")"
           TAG="sdk-v${VERSION}"
 
@@ -119,7 +124,7 @@ tag:sdk-release:
           git config user.name "GitLab CI"
           git config user.email "gitlab-ci@solvimon.invalid"
           git tag "$TAG" "$CI_COMMIT_SHA"
-          git push "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "$TAG"
+          git push "https://${SDK_RELEASE_USERNAME}:${SDK_RELEASE_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "$TAG"
     rules:
         - if: '$CI_COMMIT_BRANCH == "main"'
 
